//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoVenta.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_W
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO_W()
        {
            this.PEDIDOS_DETALLE_W = new HashSet<PEDIDOS_DETALLE_W>();
        }
    
        public string SKU { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> EXISTENCIA { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDOS_DETALLE_W> PEDIDOS_DETALLE_W { get; set; }
    }
}
